image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
after_build:
- cmd: dotnet publish --output src\Web\publicar --configuration Release && dir src\Web
artifacts:
- path: src\Web\publicar\**\*.*
  name: Publicar_WebDeploy
  type: WebDeployPackage
