image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - ECHO %APPVEYOR_BUILD_WORKER_IMAGE%
  - dotnet --version
  - dotnet restore
build_script:
  - dotnet build
after_build:
- cmd: dotnet publish src\Web\ --output publicar --configuration Release && 7z a src\Web\e-municipal-%APPVEYOR_BUILD_VERSION%.zip src\Web\publicar\* && dir src\Web
artifacts:
- path: src\Web\e-municipal-%APPVEYOR_BUILD_VERSION%.zip
  name: Publicar_WebDeploy
  type: Zip
